export const DASHBOARD_GET_USER_INFO_REQUEST = "DASHBOARD_GET_USER_INFO_REQUEST";
export const DASHBOARD_GET_USER_INFO_SUCCESS = "DASHBOARD_GET_USER_INFO_SUCCESS";
export const DASHBOARD_GET_USER_INFO_ERROR = "DASHBOARD_GET_USER_INFO_ERROR";